# Generated by Django 4.1.7 on 2023-03-22 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('user_balance', models.BigIntegerField(default=0)),
                ('operation_response', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.operation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
