# Generated by Django 4.1.7 on 2023-03-04 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
        ('operations', '0003_alter_operation_type'),
        ('records', '0002_alter_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='operation_id',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user_id',
        ),
        migrations.AddField(
            model_name='record',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.operation'),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
        ),
    ]
