# Generated by Django 4.1.7 on 2023-03-18 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ADD', 'Addition'), ('SUB', 'Subtraction'), ('MUL', 'Multiplication'), ('DIV', 'Division'), ('SQR', 'Squareroot'), ('RDM', 'Random')], max_length=3, unique=True)),
                ('cost', models.BigIntegerField()),
            ],
        ),
    ]
