# Generated by Django 4.1.7 on 2023-03-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ADD', 'Addition'), ('SUB', 'Subtraction'), ('MUL', 'Multiplication'), ('DIV', 'Division'), ('SQR', 'Squareroot'), ('RDM', 'Random')], max_length=3)),
                ('cost', models.BigIntegerField()),
            ],
        ),
    ]
