# Generated by Django 4.1.7 on 2023-03-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_operation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('ADD', 'Addition'), ('SUB', 'Subtraction'), ('MUL', 'Multiplication'), ('DIV', 'Division'), ('SQR', 'Squareroot'), ('RDM', 'Random')], max_length=3, unique=True),
        ),
    ]
