# Generated by Django 4.1.7 on 2023-03-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('I', 'Active'), ('O', 'Inactie')], default='O', max_length=1)),
            ],
        ),
    ]
